### ISSUE TITLE
consider combining `setup[Mac|Linux].sh` scripts

### ISSUE THREAD

**Issue by billimek** [WRMilling/dotfiles#1]
You can do a simple OS check that is portable via something like:

```shell
if [[ "$OSTYPE" == "darwin"* ]]; then
    # do MacOs stuff
else
    # do linux stuff
fi
```

**Comment by WRMilling** [comment]
I kind of like them separate, but I see the utility of the single file. What do you think of PR #2?

**Comment by WRMilling** [comment]
Decided to run forward with it, let me know if you have any more suggestions.
